#!/bin/bash
#Name: Chris Flores
#Date: 3/7/2021
#Title: Lab1 –add area of circle 
#Description: Lab sample to get us started using linux/bash 

echo Executing $0
echo $(/bin/ls | wc -l) files
wc -l $(/bin/ls)
echo "HOME="$HOME
echo "USER="$USER
echo "PATH="$PATH
echo "PWD="$PWD
echo "\$\$"=$$
user=`whoami`
numusers=`who | wc -l`
echo "Hi $user! There are $numusers users logged on."
if [ $user = "chris" ]
then
	echo "Now you can proceed!"
else
	echo "Check who logged in!"
	exit 1
fi

response="Yes"
while [ $response != "No" ];
do
	echo "Enter height of rectangle:"
	read height
	echo "Enter width of rectange:"
	read width
	area=`expr $height \* $width`
	echo "The area of the rectangle is $area"

	 echo "Enter radius of circle:"
        read radius
        areaC=$(bc <<< "$radius * $radius * 3.14")
	echo "The area of circle is $areaC"
	echo "Would you like to repeat[Yes/No]?"
	read response

done
