CC = g++

CFLAGS = -D DEBUG

all: lab3_1 lab3_2 lab3_3

lab3_1: lab3_1.c
	gcc $(CFLAGS) -o lab3_1 lab3_1.c
	
lab3_2: lab3_2.c
	gcc $(CFLAGS) -o lab3_2 lab3_2.c
	
lab3_3: lab3_3.c
	gcc $(CFLAGS) -o lab3_3 lab3_3.c
	
clean:
	rm -f lab3_1 lab3_2 lab3_3
